source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ALXSFValidator_Example', :exclusive => true do
  pod 'ALXSFValidator', :path => '../'
end

target 'ALXSFValidator_Tests', :exclusive => true do
  pod 'ALXSFValidator', :path => '../'

  
end
